### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by tmrouse** [garak/electron-symfony#1]
I just get:

PHP server not started. Retrying...

In console when i run npm start

**Comment by garak** [comment]
Are you sure that you pointed correctly in the "bin" option?

**Comment by tmrouse** [comment]
I will check again in the morning. 

Another question tho does this work after the app has been packaged up as I have tryed a older node package that created a php server but it breaks when it's packaged up using electron packanger  has this been tested? If so what was used to package the app. Thanks any help is really appreciated.

**Comment by garak** [comment]
I tried to build a package some times ago, then gave up. If you manage to get it working, I hope you'll share your experience here.

**Comment by tmrouse** [comment]
Will do

**Comment by Pimon1** [comment]
Still works. I also got this error, but you need to take care of your configuration in `main.js`.

- for development purposes, put the output of `which php` (probably `/usr/bin/php`) to `bin` (line 14)
- make sure you get the paths right. In the default setting, make sure to create the directories (`mkdir -p project/web`, see line 11) and put a php file called `app_dev.php` (line 38) in the `project/web` directory.

Now it should work. I'm still having the problem that I need to reload the app once it started to see any output.

**Comment by tonijota** [comment]
FYI

I cloned the repo and got working with a Symfony 6 and PHP 8 with any complication
